name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name (e.g. srb2)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine which subdirectory of AppImage/ was changed
        id: changed
        run: |
          echo "::set-output name=package::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -o 'AppImage/[^/]*' | head -n 1)"

      - name: Create AppImage from Alpine
        run: |
          cd AppImage/
          make PACKAGE=${{ github.event.inputs.package || steps.changed.outputs.package }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: AppImage/${{ github.event.inputs.package || steps.changed.outputs.package }}/out/*.AppImage
