name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name (e.g. srb2)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show which package the last commit changed; fall back to appstream package
        id: changed
        run: |
          git diff --name-only HEAD~1..HEAD | grep 'AppImage/' | cut -d/ -f2 | head -n 1 || echo 'appstream'
          echo "::set-output name=package::$(git diff --name-only HEAD~1..HEAD | grep 'AppImage/' | cut -d/ -f2 | head -n 1 || echo 'appstream')"

      - name: Create AppImage from Alpine
        run: |
          cd AppImage/
          make PACKAGE=${{ github.event.inputs.package || steps.changed.outputs.package }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: AppImage/${{ github.event.inputs.package || steps.changed.outputs.package }}/out/*.AppImage
