name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name (e.g. appstream)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # So we can diff against the previous commit

      - name: Show which package the last commit changed; fall back to appstream package
        id: changed
        run: |
          git diff --name-only HEAD~1

      - name: Create AppImage from Alpine
        run: |
          cd AppImage/
          make PACKAGE=${{ github.event.inputs.package || 'appstream' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: AppImage/${{ github.event.inputs.package || 'appstream' }}/out/*.AppImage
