name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name (e.g. srb2)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create AppImage from Alpine
        run: |
          cd AppImage/${{ github.event.inputs.package || 'srb2' }}
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: srt2-appimage
          path: AppImage/${{ github.event.inputs.package || 'srb2' }}/out/*.AppImage
